baseURL = 'https://example.org/'
languageCode = 'zh'
#defaultContentLanguage = 'zh'
title = '热带螃蟹'
theme = 'PaperMod'





[[menu.main]]
identifier = "categories"
name = "Categories"
url = "/categories/"
weight = 10

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 20


[[menu.main]]
identifier = "archives"
name = "Archives"
url = "/archives/"
weight = 10

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[[menu.main]]
identifier = "search"
name = "Search"
url = "/search/"
weight = 10

[params.homeInfoParams]
Title = "先随便坐！要喝点什么？"
Content = "|\n\n「热带螃蟹」，来自tropic of cancer，其本意为北回归线，和夏至日相对应。\n\n \n\n 仅管我更喜欢冬至日，但是热带山羊不如热带螃蟹好听。 \n\n|\n\n 多谢[@Leto](https://kaseeia-hsu.github.io/) 和 [@Catbaron](https://blog.catbaron.com/)在建站时提供的帮助 \n\n | \n\n Insta | AM | Douban | NeoDB | RSS "


[[params.socialIcons]]
name = "instagram"
url = "https://www.instagram.com/_tangerinetn/"

[[params.socialIcons]]
name = "applemusic"
url = "https://music.apple.com/profile/aerosolTn/"



[[params.socialIcons]]
name = "letterboxd"
url = "https://www.douban.com/people/133652048/"

[[params.socialIcons]]
name = "guruShots"
url = "https://neodb.social/users/azerothtn/"

[[params.socialIcons]]
name = "rss"
url = "https://aeoliantn.github.io/index.xml"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
ShowBreadCrumbs = false
ShowReadingTime = true
ShowPostNavLinks = true
ShowWordCount = true
ShowLastMod = true
ShowToc = false
comments = true
#defaultTheme = auto



[params.assets]
disableFingerprinting = true
disableHLJS = true
favicon = "/assets/favicon.ico"
favicon16x16 = "/assets/favicon-16x16.png"
favicon32x32 = "/assets/favicon-32x32.png"
apple_touch_icon = "/assets/apple-touch-icon.png"
