baseURL = 'https://example.org/'
languageCode = 'zh-CN'
title = '热带螃蟹'
theme = 'PaperMod'



[[menu.main]]
identifier = "categories"
name = "Categories"
url = "/categories/"
weight = 10

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 20


[[menu.main]]
identifier = "archives"
name = "Archives"
url = "/archives/"
weight = 10

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[[menu.main]]
identifier = "search"
name = "Search"
url = "/search/"
weight = 10

[params.homeInfoParams]
Title = "Hi there wave"
Content = "施工中；鸣谢：[Leto](https://kaseeia-hsu.github.io/){:target="_blank"} & [Catbaron](https://blog.catbaron.com/){:target="_blank"} "

[[params.socialIcons]]
name = "instagram"
url = "https://www.instagram.com/"

[[params.socialIcons]]
name = "applemusic"
url = "https://beta.music.apple.com/jp/new?l=en/"

[[params.socialIcons]]
name = "rss"
url = " "

[[params.socialIcons]]
name = "letterboxd"
url = "https://www.douban.com/people/133652048/"

[params]
ShowBreadCrumbs = true
ShowReadingTime = true
ShowPostNavLinks = true
ShowWordCount = true
